language: cpp

git:
  submodules: true
  quiet: false
  depth: false

compiler: gcc
dist: xenial
cache: ccache

before_install:
  -   add-apt-repository -y ppa:ubuntu-toolchain-r/test
  -   apt-get update -qq

install:
  -   apt-get install -qq g++-5

before_script:
  - bash scripts/install_dependencies.sh

script:
  - pwd
  - cd src/apollo
  - mkdir -p build
  - cd build && cmake ..
  - make -j$(nproc)
  -   make install
  - cd ../../../
  - bash run_all_test.bash

notifications:
  email: false
